### ISSUE TITLE
Synchronize original list with pip package

### ISSUE THREAD

**Issue by ar-anvd** [di/disposable-email-domains#8]
Hello

Do you have any plan to keep both projects synchronized automatically? That would be great.

Just replicate this [file](https://github.com/martenson/disposable-email-domains/blob/master/disposable_email_blacklist.conf). 

Ty

**Comment by di** [comment]
I don't currently have any plans to automate the updates. Currently it is a very brief manual process.

Do you have any proposal for how it should be done?

**Comment by ar-anvd** [comment]
> Do you have any proposal for how it should be done?

Thanks for the reply. My experience with github is limited, but I think that we can do something like [this](https://stackoverflow.com/questions/4414140/git-auto-pull-using-cronjob)

1. Crawl this [url](https://raw.githubusercontent.com/martenson/disposable-email-domains/master/disposable_email_blacklist.conf) 

2. Update local dev environment with the data from crawl 

3. Run a cron weekly, for example, to keep local project synchronized with [original](https://raw.githubusercontent.com/martenson/disposable-email-domains/master/disposable_email_blacklist.conf) source. Then update this project based in local project.

What do you think?

**Comment by di** [comment]
At the moment, I update this package within ~24 hours of changes made to the parent repo. A cron job running weekly would be less responsive (but perhaps more dependable).

I would rather have updates coincide with merge events in the source repo than have to periodically crawl it.

Furthermore, I'm not too interested in maintaining some kind of infrastructure for this, especially because said infrastructure would need the ability to upload a package to PyPI with my credentials.

It may be possible to do this with a CI like Travis, although I haven't looked into it. If there was a solution which fit my concerns though, I'd be very open to it.

**Comment by SethMichaelLarson** [comment]
Idea: Use Travis' cron feature to poll daily and then on failure send you an email? Then at least you'll get notified when a change occurs.

**Comment by di** [comment]
@SethMichaelLarson Thanks for the suggestion, but I already get email notifications when pull requests are merged into the parent repo, so I'm not sure what the difference would be.

However travis cron jobs could work if they could be configured to both push changes to this repo and a new release to PyPI.

**Comment by SethMichaelLarson** [comment]
Oh sure, disregard my suggestion then.
I will say that you can configure Travis to push to this GitHub repository, just use secure environment variables for one of your jobs and set that job to cron-only? And from there you can also use the `deploy: pypi` Travis config option.

**Comment by di** [comment]
This is effectively done now, #18 was a fully automated PR and release. This uses a Travis cron job to check for changes from the source repo and make a pull request if necessary. I manually merge the PR, and it get automatically deployed to PyPI.
